version: 2

aliases:
  - &restore_yarn_cache
    name: Restore yarn cache
    keys:
      - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - yarn-packages-{{ .Branch }}
      - yarn-packages-
  - &save_yarn_cache
    name: Save yarn cache
    paths:
      - ~/.cache/yarn
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
  - &filter_master
    branches:
      only: master
  - &attach
    at: ~/project

jobs:
  build:
    docker:
      - image: circleci/node:12.16.3
      - image: qlikcore/engine:12.1126.0
        command: -S AcceptEULA=yes
      - image: browserless/chrome:1.33.1-puppeteer-1.19.0

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache: *restore_yarn_cache

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Build
          command: yarn run build

      - run:
          name: Lint
          command: yarn run lint

      - run:
          name: Unit tests
          command: |
            yarn jest --coverage --reporters=default --reporters=jest-junit
            if [ ! -z "$COVERALLS_REPO_TOKEN" ]; then
              echo "Uploading coverage results to coveralls.io..."
              cat ./coverage/lcov.info | npx coveralls
            fi
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./coverage/junit/

      - run:
          name: Integration tests
          command: yarn test:rendering

      - store_artifacts:
          path: ./test/integration/__artifacts__

      - store_test_results:
          path: coverage/junit

      - save_cache: *save_yarn_cache
