name: Api Compliance
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Run api compliance
        uses: qlik-oss/sn-gh-workflows/actions/api-governance@jnl/api_governance
        with:
          API_KEY: ${{ secrets.API_KEY }}
          API_SPECIFICATION_PATH: api-specifications/properties.json
          APICULTURIST_GITHUB: ${{ secrets.APICULTURIST_GITHUB }}
          APICULTURIST_S3: ${{ secrets.APICULTURIST_S3 }}
          APICULTURIST_TOKEN: ${{ secrets.APICULTURIST_TOKEN }}
          TAG: ${{ inputs.tag }}
